### ISSUE TITLE
The checkpoint models might be corrupted.

### ISSUE THREAD

**Issue by xleslie** [fei-hdu/ca-gan#12]
Hi, when I used your pre-training model to test, I  encountered  a problem
"RuntimeError: unexpected of. The file might be corrupted."

Traceback (most recent call last):
  File "test.py", line 20, in <module>
    netG.load_state_dict(torch.load('./checkpoint/netG_epoch_'+fold+'.weight'))
  File "/home/xuyidan/.conda/envs/cagan/lib/python2.7/site-packages/torch/serialization.py", line 358, in load
    return _load(f, map_location, pickle_module)
  File "/home/xuyidan/.conda/envs/cagan/lib/python2.7/site-packages/torch/serialization.py", line 549, in _load
    deserialized_objects[key]._set_from_file(f, offset, f_should_read_directly)
RuntimeError: unexpected EOF. The file might be corrupted.

**Comment by aryachiranjeev** [comment]
@xleslie did you get the correct weights file. I am also facing same error "Corrupt file". 
@fei-hdu

**Comment by xalteropsx** [comment]
return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)                                                                                            
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                            
  File "Z:\software\python11\Lib\site-packages\torch\serialization.py", line 1327, in _legacy_load                                                                               
    typed_storage._untyped_storage._set_from_file(                                                                                                                               
RuntimeError: unexpected EOF, expected 13178402 more bytes. The file might be corrupted.  

netG_epoch_700.weight
@fei-aiart  bro netG was currpted netE work fine  // download by google drive

also need dataset in google drive bro
